export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_ALUNOS = 'GET_ALUNOS';
export const GET_ALUNO = 'GET_ALUNO';
export const LIMPAR_ALUNO = 'LIMPAR_ALUNO';
export const CANCELAR_ALUNO = 'CANCELAR_ALUNO';

export const GET_FUNCIONARIOS = 'GET_FUNCIONARIOS';
export const GET_FUNCIONARIO = 'GET_FUNCIONARIO';
export const LIMPAR_FUNCIONARIO = 'LIMPAR_FUNCIONARIO';
export const CANCELAR_FUNCIONARIO = 'CANCELAR_FUNCIONARIO';

export const GET_CHAPAS = 'GET_CHAPAS';
export const GET_CHAPA = 'GET_CHAPA';
export const LIMPAR_CHAPA = 'LIMPAR_CHAPA';
export const CANCELAR_CHAPA = 'CANCELAR_CHAPA';

export const GET_CANDIDATOS = 'GET_CANDIDATOS';
export const GET_CANDIDATO = 'GET_CANDIDATO';
export const LIMPAR_CANDIDATO = 'LIMPAR_CANDIDATO';
export const CANCELAR_CANDIDATO = 'CANCELAR_CANDIDATO';
